// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoreBaseApiChallenge.Infrastructure.Repository;

#nullable disable

namespace NoreBaseApiChallenge.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241103162530_row-version3")]
    partial class rowversion3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.35");

            modelBuilder.Entity("NoreBaseApiChallenge.Domain.entity.Like", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("LikeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("DATETIME('now')");

                    b.HasKey("ArticleId");

                    b.ToTable("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
